### ISSUE TITLE
This image doesn't seem to work

### ISSUE THREAD

**Issue by geoidesic** [panubo/docker-sshd#13]
Step 4/6 : COPY entry.sh /entry.sh
COPY failed: stat /var/lib/docker/tmp/docker-builder114673644/entry.sh: no such file or directory

**Comment by macropin** [comment]
I can build this image just fine. There are actually *7* steps in the `Dockerfile` so you must be building your own version. FWIW that error indicates that `entry.sh` was not found within the build context.

Maybe use the prebuilt container `docker.io/panubo/sshd`
