### ISSUE TITLE
Tagged Releases

### ISSUE THREAD

**Issue by timothyclarke** [panubo/docker-sshd#16]
Can you create tags (and builds for them in https://hub.docker.com/r/panubo/sshd/) 
I'm looking to use the container, but generally don't like rolling tags like "latest" as unexpected changes can happen. 
Can you both tag commits every now and again, and also create builds on dockerhub so when you tag commits here it produces appropriate tags there?

Thanks

**Comment by macropin** [comment]
Release `1.0.0` has been made. And it's now on the hub `docker.io/panubo/sshd:1.0.0`. We'll continue to make semver'd releases as appropriate.

**Comment by antoniogomezalvarado** [comment]
@macropin hi! is the version that was in place during 31/3 still available somewhere? Suddenly sshing with the root account gets prompted with a password, any idea what might have changed that?

**Comment by macropin** [comment]
@antoniogomezalvarado please open a separate issue for this thanks.
