### ISSUE TITLE
SFTP_CHROOT is ignored

### ISSUE THREAD

**Issue by mpdn** [panubo/docker-sshd#17]
The environment variable is not actually used to set the chroot path. See: http://github.com/panubo/docker-sshd/blob/aa347246ceae6af44d465c2399f8a67a2aed8306/entry.sh#L104

An easy workaround is of course just to mount the dir you want to chroot into on `/data`.

**Comment by macropin** [comment]
Thanks for reporting. Fixed in the above commit.
