### ISSUE TITLE
Can't login as root since last update

### ISSUE THREAD

**Issue by gionn** [panubo/docker-sshd#20]
Hi,

my CI build broken a few hours ago, it looks like that doing what stated in README is not working anymore:

```
docker run -d -p 2222:22 -v /secrets/id_rsa.pub:/root/.ssh/authorized_keys -v /mnt/data/:/data/ docker.io/panubo/sshd
```

**Comment by macropin** [comment]
I believe this is due to the change to `alpine:3.6` which was made quite some time ago in 67d10431604e2934eba67c2398bb9b94e0b87267.

Alpine now lock the root account by default. Fix incoming.

**Comment by gionn** [comment]
I was pulling `panubo/sshd:latest`, probably the tag has been updated only today.

Thanks.

**Comment by macropin** [comment]
We have release tags now to prevent issues like this. Try `panubo/sshd:1.0.1`

**Comment by antoniogomezalvarado** [comment]
@macropin `1.0.1`  still prompts a password for root and enabling `SSH_ENABLE_ROOT` makes the ssh connection stuck on `debug1: Local version string SSH-2.0-OpenSSH_7.4`

Is it possible to make a legacy version?

**Comment by macropin** [comment]
@antoniogomezalvarado I think this is a different issue. Can you please open a new issue and post the full debug output. Thanks.
