### ISSUE TITLE
Please disable password authentication

### ISSUE THREAD

**Issue by lordpengwin** [panubo/docker-sshd#24]
I know this is probably harmless but I'd like to see a fast failure when someone tries to log in without a key. As it stands doing a: 

% ssh root@xxx.xxx.xxx.xx

results in a password prompt. Setting the following in sshd_config causes an immediate failure

PasswordAuthentication no

**Comment by macropin** [comment]
Happy to take a PR for this, with the default set to enabled. I'm pretty sure that some of our users still use password auth.

**Comment by lordpengwin** [comment]
Actually I realized that it is just as easy to override the command and set the options that I wanted there.
e.g. /usr/sbin/sshd -o 'SyslogFacility=AUTHPRIV' -o 'PermitRootLogin=no' -o 'PasswordAuthentication=no' -D -f /etc/ssh/sshd_config

Note: if you also add a volume -v /dev/log:/dev/log you get full logging to syslog on the host machine which is really useful if you use fail2ban.
