### ISSUE TITLE
Upgrading alpine:3.6 dependency?

### ISSUE THREAD

**Issue by mgrzechocinski** [panubo/docker-sshd#25]
Hi. 

In my environment, I'm extending this image to build my custom Jenkins slave image for the purpose of validating OpenAPI spec. My Docker file looks like this:

```
FROM panubo/sshd

RUN apk add --update nodejs-npm \
  && npm install -g swagger-cli@2.2.1 \
  && npm install -g json-merger
```

I'm forced to use swagger-cli 2.2.1 because starting from swagger-cli 2.2.2, there's an issue of too old version of nodejs which is (as I guess) the last available version for alpine 3.6, which this image is extending from:
https://github.com/panubo/docker-sshd/blob/1f680b30d47f709ed9d105b0d746a41611948357/Dockerfile#L1

Are there any plans to upgrade alpine dependency to the newest version (3.10.1 as of writing this post)?

**Comment by macropin** [comment]
Closed with 3fe31035c86e7b01f2d79884ac87b0360de71440
