### ISSUE TITLE
GATEWAY_PORTS enviroment variable not working

### ISSUE THREAD

**Issue by jesushg-smartway** [panubo/docker-sshd#29]
Hi,

I set GATEWAY_PORTS=true, my reverse port forwarding only listen in localhost (127.0.0.1).
I edit /etc/ssh/sshd_config in container, setting GatewayPorts yes and works my reverse port forwarding.

Pls fix this issue :D

**Comment by seanw2020** [comment]
I have the same problem.

**Comment by macropin** [comment]
@jesushg-smartway That's exactly what `-e GATEWAY_PORTS=true` does it sets  `GatewayPorts yes` in `/etc/ssh/sshd_config`. 

Was there something else that you needed to configure?

**Comment by macropin** [comment]
Closing for now as support for `AllowTcpForwarding` has been added. Feel free to reopen if you have further information about your issue.
