### ISSUE TITLE
Can't get nailgun to work with this image

### ISSUE THREAD

**Issue by danuvian** [panubo/docker-sshd#31]
I am using your image along with Open JDK 11 and "nailgun" (a Java program). When I run the nailgun client with the parameter ng-cp, I do not get back any output. I have tested nailgun with Centos 8 and a brand new version of Alpine without your code, and it works fine. Can you assist? Thank you.

**Comment by macropin** [comment]
Sorry, we can't provide support. Unless this is a bug report, in which case feel free to provide more information.
