### ISSUE TITLE
[question] logging in with password - how to set it up

### ISSUE THREAD

**Issue by eleaner** [panubo/docker-sshd#39]
It is maybe a bit stupid question but how do I define what the password is?
is it something extra in SSH_USERS?

I know that SSH_ENABLE_PASSWORD_AUTH=true is required

**Comment by Kamori** [comment]
I ran into this tonight. I noticed the Custom scripts section here
https://github.com/panubo/docker-sshd#custom-scripts

So what I did was create a custom script that ran chpasswd for the user I had created

Here is the example
```
docker run -ti -p 2222:22 \
  -e SSH_USERS=admin:1000:1000 \
  -e SSH_ENABLE_PASSWORD_AUTH=true \
  -v $(pwd)/entrypoint.d/:/etc/entrypoint.d/ \
  docker.io/panubo/sshd:1.1.0
```

and in my $(pwd)/entrypoint.d/ I made setpassword.sh

```
echo "admin:testings" | chpasswd
```

Now I can login with my password testings
```
ssh -p 2222 admin@127.0.0.1
admin@127.0.0.1's password: 
Welcome to Alpine!

The Alpine Wiki contains a large amount of how-to guides and general
information about administrating Alpine systems.
See <http://wiki.alpinelinux.org/>.

You can setup the system with the command: setup-alpine

You may change this message by editing /etc/motd.

04c81e500a57:~$ 
```

**Comment by eleaner** [comment]
@Kamori 
thank you, this will do

**Comment by macropin** [comment]
Please see PR above for preferred approach using password hash rather than plaintext passwords.
