### ISSUE TITLE
SSH with new users

### ISSUE THREAD

**Issue by amortenson** [panubo/docker-sshd#4]
If I create new users and add ~[USERNAME]/.ssh files for them in the Dockerfile, I can't seem to figure out how to modify entry.sh in a way that allows me to ssh into them properly. As of now, I can ssh but I immediately get disconnected. This is what I see:

```
tux@localhost's password: 
Welcome to Alpine!

The Alpine Wiki contains a large amount of how-to guides and general
information about administrating Alpine systems.
See <http://wiki.alpinelinux.org>.

You can setup the system with the command: setup-alpine

You may change this message by editing /etc/motd.

Connection to localhost closed.
```

My fork of this repo contains the base code I'm working with.

**Comment by macropin** [comment]
Currently there isn't any explicit support for this. I suppose you could mount `/etc/passwd`, `/etc/group` and `/home`. And as long as the permissions are right it should work. However I think a more correct approach would be to add support for USERS environment variable in the form `<username>:<uid>:<gid>`... This would still require keys to be present and /home mounted (or individual .ssh dirs).

Does this fit your use case? Or would you rather build on top of this image?

Btw, I couldn't find your fork..

**Comment by amortenson** [comment]
I'll look into this, thanks, but I'd rather build on top. This isn't as essential a feature for us as some, so it may get pushed down the road. Sorry about the fork thing. You couldn't find it because my fork is inside an org, my bad... 
https://github.com/learnlinux/docker-sshd

PS yes I know I've mangled your code. I apologize profusely.

**Comment by macropin** [comment]
I've had a look at your repo, and to be honest I don't think we'd want to support password auth out of the box.

If you wanted multiple users with key based auth I think I can add that in. A better approach for that might be to stat /home and create user accounts based off what is found mounted there.

**Comment by liselorev** [comment]
warning
the entry.sh contains a test

    [ -e " /etc/authorized_keys/${_USER}" ]

the leading space (before the /) must be removed, otherwise the test will always fail.

**Comment by macropin** [comment]
@liselorev this fix has been implemented

Closing as this ssh-users has been merged.
