### ISSUE TITLE
Sendmail from inside the docker image

### ISSUE THREAD

**Issue by bertalanimre** [panubo/docker-sshd#47]
I have a problem with sending email from the docker image. What I'm trying is to create a txt file with sender, recepient, subject, body and then send it with sendmail. But all I get always is: 

```
bash-5.0# sendmail -vt < mail.txt 
sendmail: can't connect to remote host (127.0.0.1): Connection refused
```

Any idea how can I use sendmail inside the docker?

**Comment by macropin** [comment]
There is no mail daemon installed or running within this image. If you wish to send email you'll need to either set that up yourself, or connect to an external SMTP service. `mailx` should be able to do this, but support for this is out of scope.
