### ISSUE TITLE
authorized_keys:ro

### ISSUE THREAD

**Issue by shannonrdunn** [panubo/docker-sshd#5]
-v /secrets/id_rsa.pub:/root/.ssh/authorized_keys:ro

Was having a problem here, I think having read only on that will stop your entrypoint.sh from changing to proper permissions root:root 0600. 

I was getting 
auth.info sshd[37]: Authentication refused: bad ownership or modes for file /root/.ssh/authorized_keys

Works after taking the :ro away from the docker run command

**Comment by maelvls** [comment]
Thank you for the tip! I had the same issue and just had to remove the `:ro` part.

Thank you again!!!
