### ISSUE TITLE
[Solved] Cannot log in using password script

### ISSUE THREAD

**Issue by zklosko** [panubo/docker-sshd#57]
In the readme, you suggest:

>Password authentication is not recommended however using `SSH_ENABLE_PASSWORD_AUTH=true` you can enable password authentication. The image doesn't provide any way to set user passwords via config but you can use the custom scripts support to run a custom script to set user passwords.

My script (which looks similar to the one provided; thanks guys):
```
#!/usr/bin/env bash

set -e

echo 'user1:$6$lAkdPbeeZR7YJiE3$ohWgU3LcSVit/hEZ2VOVKvxD.67.N9h5v4ML7.4X51ZK3kABbTPHkZUPzN9jxQQWXtkLctI0FJZR8CChIwz.S/' | chpasswd --encrypted

echo 'test:test' | chpasswd
```

By passing this in using `docker run -ti --publish 2222:22
  -v /.../sshd/keys/:/etc/ssh/keys
  -e SSH_USERS=user1:1012:1112,test:1013:1113
  -e SSH_ENABLE_PASSWORD_AUTH=true 
  -v /.../sshd/entrypoint.d/:/etc/entrypoint.d/ 
  panubo/sshd`, I keep getting `Failed password for test from 172.17.0.1 port 51866 ssh2` as an error message during login attempts. I try to log into both *user1* and *test* users with the passwords as provided above. No dice. Any ideas?

P.S. I did check the file system by attaching to the container. Docker did mount the script in at container launch.

**Comment by zklosko** [comment]
I did find a work-around, and I'll leave this issue open so others can see it.

Passed files to /etc/entrypoint.d do not get run at container start. A way to fix this is to have the script execute at image build.

Script:
```
#!/usr/bin/env bash

set -e

adduser -D --no-create-home user
echo 'user:test' | chpasswd
```

Dockerfile:
```
FROM panubo/sshd
MAINTAINER Zachary Klosko (kloskoz@vcu.edu)

COPY setpasswd.sh /
RUN bash setpasswd.sh

CMD ["/usr/sbin/sshd", "-D", "-e", "-f", "/etc/ssh/sshd_config"]
```

**Comment by yuzuki-ayase** [comment]
https://github.com/panubo/docker-sshd/blob/a3ad2702752e2c2a88d3c4b265744405f2c66fae/entry.sh#L201-L204

Because this code doesn't work. It does not think scripts is executable file. And then I have tried and searched a lot, and found this:

```shell
$ ls -tlr entrypoint.d/
total 4
-rw-rw-r-- 1 xiaojie xiaojie 196 Oct 25 23:18 setpasswd.sh
```

My script have not executable right.  You can give it right to solve this problem.

```shell
chmod u+x entrypoint.d/setpasswd.sh
```
