### ISSUE TITLE
Group Add fails when a user has an existing group number

### ISSUE THREAD

**Issue by kitobelix** [panubo/docker-sshd#60]
`>> Adding user user1 with uid: 1000, gid: 1000, shell: <default>.
16/11/2020 16:05:41>> Adding user user2 with uid: 1001, gid: 1000, shell: <default>.
16/11/2020 16:05:41groupadd: GID '1000' already exists`

And container exits. I suggest to do a fix by using `getent group ${_GID} >/dev/null 2>&1 || { groupadd -g ${_GID} ${_NAME} }` instead.

Many thanks for your exceptional work.

**Comment by macropin** [comment]
What sort of use case causes this issue to arise? Are you building on top of this image and adding users during the build?

**Comment by kitobelix** [comment]
Hello! I'm using it as is, to allow some users to access files stored locally without giving full access to Host. That error came when I used the env var `SSH_USERS` with two users with the same group number (like `SSH_USERS=user1:1000:1000,user2:1001:1000` )

Thank you for answering! I solved it manually by mounting an external entry.sh until there is a solution (if this is an issue, of course).
