### ISSUE TITLE
Connection Refused from WAN

### ISSUE THREAD

**Issue by wiryonolau** [panubo/docker-sshd#62]
Hi I've been using this to gave ssh access for support.
This week suddenly it got this message, whenever we want to open connection outside docker host

```bash
telnet: Unable to connect to remote host: Connection refused
```
I use your script inside my custom container cause it need php and other stuff. I thought it was my script so I run directly using your image 

```bash
docker run --rm \
  -e SSH_USERS=test:1000:1000:/bin/bash \
  -e SSH_ENABLE_PASSWORD_AUTH=true \
  -v $(pwd)/setpasswd.sh:/etc/entrypoint.d/setpasswd.sh \
  -p2222:22 \
panubo/sshd
```

setpasswd.sh contain the password
```bash
#!/usr/bin/env bash
set -e
echo "test:888888" | chpasswd
```

FIrewall is disabled

**Comment by macropin** [comment]
This is almost certainly a networking issue rather than a config / bug with the image.
