### ISSUE TITLE
implement auth log

### ISSUE THREAD

**Issue by mfilser** [panubo/docker-sshd#69]
Hello,
first, thanks a lot for this very useful container, it work's very well.

I see on the standard-output that i have a lot of invalid login attempts. I want to secure it with fail2ban, and i need to read the file /var/log/auth.log, but it itsn't there.

Is there an option to enable / implement this?

Thank you in advance,
best regards,
Martin

**Comment by pragmatic** [comment]
Hi Martin,

Thank you for your kind words.

It's out of the scope of this project to implement a logging system, which would be required to expose the log file that fail2ban's logpath wants.

There's a couple of options you can investigate:

1. Look in your hosts Docker container log`/var/lib/docker/containers/<CONTAINERID>/<CONTAINERID>-json.log`.  This file contains JSON formatted output from the Docker daemon.
2. Configure a [Docker log driver](https://docs.docker.com/config/containers/logging/configure/#supported-logging-drivers) to run your container with.  The syslog or journald drivers may be of most use to you.

Hope that helps.

**Comment by BasixKOR** [comment]
Could we have a reconsideration? I'm experiencing an authentication issue and without the auth.log it is too much hassle to debug it.

**Comment by mfilser** [comment]
@BasixKOR 
If you like you could try to clone from my repository https://github.com/mfilser/docker-sshd which contains the PR #75, build the image and see if it work's for you too.
