### ISSUE TITLE
scripts in /etc/entrypoint.d are not executed 

### ISSUE THREAD

**Issue by paolino** [panubo/docker-sshd#74]
the executable test in 
```
 if [[ -x ${f} ]]; then 
     echo ">> Running: ${f}" 
     ${f} 
 fi 
```
is not passing on files with 755 permissions set 
this could be a bug in musl libc 

changing to 
```
 if [[ -f ${f} ]]; then 
     echo ">> Running: ${f}" 
     ${f} 
 fi 
``` 
is the  workaround we adopted

**Comment by kamikat** [comment]
> It seems as though Alpine 3.14 is pertinent to a known bug here.

https://unix.stackexchange.com/questions/671246/why-is-bash-not-evaluating-the-executable-bit-correctly-in-alpine-3-14-2

**Comment by macropin** [comment]
Please reopen if this continues with the latest 3.18 builds.

**Comment by montanier** [comment]
Hello,

I think that the `setpasswd.sh` part of the README should say that the permission of `setpasswd.sh` has to be set to `755`

I wanted to use the script and was wondering why it was not working. I got lucky to find out the mention about the `755` permission.
