### ISSUE TITLE
Restricted modes do not apply to root

### ISSUE THREAD

**Issue by rocktale** [panubo/docker-sshd#77]
If the root account is enabled via `SSH_ENABLE_ROOT=true` the restricted modes do not seem to apply to the root account, i.e. one can still login via SSH getting a regular shell login. After checking the entrypoint script, I realized that it only applies the restricted shell etc. to the configured users via `SSH_USERS`.

I think, this behavior should at least be documented. However, I was wondering if there is a specific reason to exclude the root account from the restricted modes since I'd prefer to use root (for simplicity with access rights for the keys files as well as the files written via rsync) but still have the added security of restricted access.

**Comment by kat1440** [comment]
How can I be restricted access if the root is everywhere sees everything knows all how in fact is there restricted access. Blank to anything if he's not restricted at all

**Comment by kat1440** [comment]
It does however put into question, how with no knowledge at all of any kind of computer training he was able to fix a Chromebook and laptop, hack through GitHub, create a login in the process, still go back to main page, and then gain access to all applications and all repository tokens, being able to regenerate token after token as he sees it fit, I do not think you are giving enough credit where credit is actually due

**Comment by macropin** [comment]
@rocktale `SSH_ENABLE_ROOT` is not recommended, we don't use it.

You might be able to achieve what you're looking for using group membership and the new #76 options. 

It's definitely possible to achieve what you want using https://github.com/panubo/docker-sshd#custom-scripts. You could create a second user with UID/GID 0 and using the restricted shell.
