### ISSUE TITLE
Rebuild image to fix terrapin vulnerability

### ISSUE THREAD

**Issue by mojo2012** [panubo/docker-sshd#84]
Hi guys,

can you a new version of the image please, to fix the terrapin vulerability. Alpine already has openssh 9.6 ready.

Cheers, matti

**Comment by trnubo** [comment]
Hi Matti,

We released https://github.com/panubo/docker-sshd/releases/tag/v1.8.0 a few days ago, it is based on Alpine 3.19 and has OpenSSH 9.6 installed. You may need to switch to quay.io/panubo/sshd or public.ecr.aws/panubo/sshd as we don't publish to Docker Hub anymore.

Cheers,

**Comment by mojo2012** [comment]
Thanks for the hint!
